this handles .gz files only, but it intersperses line number with raw data, so you get errors like:
IOError: Bad version line: '0\tWARC/1.0\r\n'

(the 0\t was added by Hadoop)

Looks like you can't tell Hadoop streaming to just cat you the file